ARG PYTHON_VERSION=3.12
FROM python:${PYTHON_VERSION}-slim

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

RUN pip install -U --no-cache-dir poetry pip && poetry config virtualenvs.create false

COPY pyproject.toml pyproject.toml
COPY poetry.lock poetry.lock

RUN poetry install --no-interaction --no-ansi --no-root --without dev


ARG APP_DB_HOST
ARG APP_DB_PORT
ARG APP_DB_NAME
ARG APP_DB_USER
ARG APP_DB_PASSWORD
ARG APP_DB_POOL_SIZE
ARG APP_DB_POOL_TIMEOUT
ARG APP_DB_DEBUG

ENV APP_DB_HOST=${APP_DB_HOST}
ENV APP_DB_PORT=${APP_DB_PORT}
ENV APP_DB_NAME=${APP_DB_NAME}
ENV APP_DB_USER=${APP_DB_USER}
ENV APP_DB_PASSWORD=${APP_DB_PASSWORD}
ENV APP_DB_POOL_SIZE=${APP_DB_POOL_SIZE}
ENV APP_DB_POOL_TIMEOUT=${APP_DB_POOL_TIMEOUT}
ENV APP_DB_DEBUG=${APP_DB_DEBUG}

ARG APP_REDIS_HOST
ARG APP_REDIS_PORT
ARG APP_REDIS_PASSWORD

ENV APP_REDIS_HOST=${APP_REDIS_HOST}
ENV APP_REDIS_PORT=${APP_REDIS_PORT}
ENV APP_REDIS_PASSWORD=${APP_REDIS_PASSWORD}

ARG APP_TG_BOT_TOKEN
ARG APP_TG_ALLOWED_CHAT_ID

ENV APP_TG_BOT_TOKEN=${APP_TG_BOT_TOKEN}
ENV APP_TG_ALLOWED_CHAT_ID=${APP_TG_ALLOWED_CHAT_ID}



COPY ./mrfixit ./mrfixit

EXPOSE 8000

ENV APP_WORKERS=1

CMD ["python", "-m", "mrfixit"]