services:
  mrfixit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mrfixit_app
    env_file:
      - .env
    ports:
      - "8001:8000"
    restart: unless-stopped

  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${APP_DB_USER}
      - POSTGRES_PASSWORD=${APP_DB_PASSWORD}
      - POSTGRES_DB=${APP_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: mrfixit_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: /bin/sh -c "redis-server --requirepass ${APP_REDIS_PASSWORD}"
    env_file:
      - .env

volumes:
  postgres_data: