"""empty message

Revision ID: 2074caa0b55c
Revises:
Create Date: 2025-06-15 16:49:04.212222

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "2074caa0b55c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tech_requests",
        sa.Column("title", sa.String(length=63), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column(
            "category",
            postgresql.ENUM("ordinary", "urgent", name="tech_request_category"),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("created", "done", name="tech_request_status"),
            nullable=False,
        ),
        sa.Column(
            "building",
            postgresql.ENUM("fort_dialog", "fontan", name="tech_request_building"),
            nullable=False,
        ),
        sa.Column("file_id", sa.String(length=512), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__tech_requests")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tech_requests")
    # ### end Alembic commands ###
